config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  root 'tournaments#index'

  resources :oauths, only: [] do
    collection do
      get :request_token
      get :access_token
    end
  end

  resources :tournaments, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/oauths_controller.rb
# frozen_string_literal: true

# Handles OAuth authentication flow
class OauthsController < ApplicationController
  before_action :set_root_url
  before_action :set_authenticator

  # Initiates the OAuth request token flow and stores the token and secret in session and redirects to authorization URL
  #
  # @return [void]
  def request_token
    request_token = @authenticator.request_token
    session[:token] = request_token.token
    session[:token_secret] = request_token.secret
    redirect_to request_token.authorize_url(oauth_callback: 'oob'), allow_other_host: true
  end

  # Exchanges the request token for an access token. Stores the access token in session and removes the temporary tokens
  #
  # @raise [OAuth::Unauthorized] if authentication fails
  # @return [void]
  def access_token
    hash = { oauth_token: session[:token], oauth_token_secret: session[:token_secret] }
    verifier = params[:oauth_verifier]
    access_token = @authenticator.get_access_token(hash, verifier)
    session[:access_token] = access_token.token
    session[:access_token_secret] = access_token.secret
    session.delete(:token)
    session.delete(:token_secret)
    redirect_to root_path, notice: 'Successful access'
  rescue OAuth::Unauthorized => e
    Rails.logger.error("OAuth error: #{e.message}")
    raise
  end

  private

  # Sets the application's root URL configuration
  #
  # @return [void]
  def set_root_url
    Rails.application.config.root_url = root_url
  end

  # Initializes the authenticator instance
  #
  # @return [void]
  # @set @authenticator
  def set_authenticator
    @authenticator = Authenticator.call
  end
end

app/controllers/tournaments_controller.rb
# frozen_string_literal: true

# Controller to handle tournament related actions
class TournamentsController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hattrick Tournaments Viewer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tournaments/index.html.erb
<h1>Torneos</h1>
<p>Al parecer es tu primera vez aquí. Ingresa</p>
<%= link_to 'aquí', request_token_oauths_path, class: 'btn' %>